'use strict';
const icons={
 mission:'<circle cx="50" cy="54" r="33"/><path d="m35 73 10-27 23-15-10 28Z" fill="url(#darkgold)"/><circle cx="51" cy="52" r="3" fill="#fff5d2" stroke="none"/><path d="m50 7 1.5 4.5H56l-3.5 3 1 4L50 16l-3.5 2.5 1-4-3.5-3h4.5Z" fill="url(#darkgold)" stroke="none"/>',
 clients:'<circle cx="37" cy="29" r="13"/><path d="M10 83c0-33 53-33 53 0"/><circle cx="72" cy="44" r="10"/><path d="M63 66c16-8 28 1 28 18"/>',
 facts:'<path d="M42 32V11a5 5 0 0 1 5-5h40a5 5 0 0 1 5 5v71a5 5 0 0 1-5 5H66M55 22h25M67 34h13M68 46h12M68 58h12M68 70h12"/><path d="M7 34h44a6 6 0 0 1 6 6v32a6 6 0 0 1-6 6H28L15 89V78H7a6 6 0 0 1-6-6V40a6 6 0 0 1 6-6Z"/><g fill="url(#gold)" stroke="none"><circle cx="15" cy="56" r="3.5"/><circle cx="29" cy="56" r="3.5"/><circle cx="43" cy="56" r="3.5"/></g>',
 faq:'<path d="M28 81 10 91l5-24a35 35 0 1 1 13 14Z"/><path d="M36 38c0-18 29-18 29 0 0 12-14 11-14 22"/><circle cx="51" cy="73" r="2" fill="url(#gold)"/>',
 rules:'<path d="M25 9h37l17 18v63H25ZM62 9v22h17M36 45h29M36 56h24M36 67h29M36 78h15"/>',
 stories:'<path d="M50 26C36 17 18 18 7 24v61c15-7 29-6 43 1 14-7 29-8 43-1V24c-14-6-30-7-43 2ZM50 26v60"/>',
 contact:'<path d="M8 22h84v61H8ZM10 24l40 33 40-33M8 83l28-30M92 83 64 53"/>',
 opinions:'<path d="M26 78 12 92l4-24A37 34 0 1 1 26 78Z"/><path d="m50 27 8 16 18 3-13 13 3 18-16-9-16 9 3-18-13-13 18-3Z" fill="url(#darkgold)" stroke="none"/>',
 documents:'<path d="M28 8h33l18 18v66H28ZM61 8v22h18M40 46h26M40 57h22M40 68h26M40 79h16"/>',
 positions:'<path d="M33 4h34a4 4 0 0 1 4 4v24a4 4 0 0 1-4 4H49L38 46V36h-5a4 4 0 0 1-4-4V8a4 4 0 0 1 4-4Z"/><g fill="url(#gold)" stroke="none"><circle cx="41" cy="20" r="2.5"/><circle cx="50" cy="20" r="2.5"/><circle cx="59" cy="20" r="2.5"/></g><circle cx="22" cy="59" r="10"/><circle cx="78" cy="59" r="10"/><path d="M2 95c1-31 39-31 40 0M58 95c1-31 39-31 40 0"/>',
 verify:'<circle cx="42" cy="42" r="30"/><path d="m27 42 10 10 21-22M64 65l28 28M68 66l24 24"/>'};
const cards=[['mission','Nasza<br>misja','cream'],['clients','Klienci','green'],['facts','Fakty i opinie','red'],['faq','FAQ<br>i pomoc','blue'],['rules','Regulaminy','burgundy'],['stories','Opowieści','green'],['contact','Kontakt','cream'],['opinions','Opinie','cream'],['documents','Dokumenty','sage'],['positions','Stanowiska<br>stron','blue'],['verify','Weryfikacja','amber']];
const branches=['opinions','documents','positions','verify'];
document.querySelector('#cards').innerHTML=cards.map(([id,title,color])=>`<button class="card ${id} ${color} ${branches.includes(id)?'branch':''}" data-card="${id}" type="button" ${id==='facts'?'aria-expanded="true" aria-controls="card-opinions card-documents card-positions card-verify"':'aria-haspopup="dialog"'} id="card-${id}"><svg class="leaf one" aria-hidden="true"><use href="#leaves"/></svg><svg class="leaf two" aria-hidden="true"><use href="#leaves"/></svg><svg class="card-icon" aria-hidden="true" viewBox="0 0 100 100">${icons[id]}</svg><span class="card-label">${title}</span></button>`).join('');
const sourceMarks={Google:'<svg viewBox="0 0 48 48" aria-label="Google"><path fill="#4285f4" d="M44 24.5c0-1.6-.1-3-.4-4.5H24v8.5h11.2c-.5 2.6-2 4.8-4.3 6.2v5.2h7C42 36.3 44 31 44 24.5Z"/><path fill="#34a853" d="M24 45c5.6 0 10.3-1.8 13.9-5.1l-7-5.2c-1.9 1.3-4.2 2-6.9 2-5.4 0-10-3.6-11.7-8.5H5.2v5.4C8.7 40.4 15.8 45 24 45Z"/><path fill="#fbbc05" d="M12.3 28.2a12.7 12.7 0 0 1 0-8.4v-5.4H5.2a21 21 0 0 0 0 19.2Z"/><path fill="#ea4335" d="M24 11.3c3 0 5.7 1 7.8 3l5.9-6C34.2 5 29.6 3 24 3 15.8 3 8.7 7.6 5.2 14.4l7.1 5.4c1.7-4.9 6.3-8.5 11.7-8.5Z"/></svg>',Booking:'<span class="booking">B.<small>Booking.com</small></span>',Booksy:'<span class="booksy">⌁Booksy</span>',Tripadvisor:'<svg viewBox="0 0 50 50" aria-label="Tripadvisor"><circle cx="25" cy="25" r="24" fill="#34e0a1"/><g fill="none" stroke="#06251c" stroke-width="2.5"><circle cx="15" cy="26" r="9"/><circle cx="35" cy="26" r="9"/><circle cx="15" cy="26" r="3"/><circle cx="35" cy="26" r="3"/><path d="m21 34 4 5 4-5M5 17l5 4M45 17l-5 4M14 16q11-8 22 0"/></g></svg>'};
// Editable content is independent from video and layout.
const opinions=[{source:'Google',name:'Restauracja',rating:'★☆☆☆☆',text:'Nie byłem, ale wiem.',position:'r1'}, {source:'Booking',name:'Hotel',rating:'1/10',text:'Bo tak.',position:'r2 left'},{source:'Tripadvisor',name:'Hotel & SPA',rating:'●○○○○',text:'Widok za ładny.',position:'r3 right'},{source:'Booksy',name:'Barber',rating:'★★☆☆☆',text:'Fryzura dobra. Pogoda słaba.',position:'r4 left'}];
document.querySelector('#reviews').innerHTML=opinions.map((r,i)=>`<button type="button" class="review ${r.position}" data-review="${i}" aria-haspopup="dialog" aria-label="Fikcyjna opinia: ${r.name}, ${r.source}, ${r.text}"><span class="review-head"><span class="review-source">${sourceMarks[r.source]}</span><span><span class="review-name">${r.name}</span><br><span class="review-rating ${r.source==='Booking'?'score':''}" ${r.source==='Tripadvisor'?'style="color:#00aa6c"':''}>${r.rating}</span></span></span><p>${r.source==='Booksy'?'Fryzura dobra.<br>Pogoda słaba.':r.text}</p></button>`).join('');
const panel=document.querySelector('#panel');
const copy={mission:['Nasza misja','Miejsce na rzetelny opis misji portalu Nasi Klienci i zasad, którymi kieruje się AsterA.'],clients:['Klienci','Tutaj znajdą się profile klientów i firm oraz powiązane z nimi informacje.'],faq:['FAQ i pomoc','Wybierz kafelek, aby otworzyć panel. „Fakty i opinie” rozwija cztery powiązane karty. Tło zatrzymuje się na czas czytania; możesz je też zatrzymać przyciskiem u dołu strony.'],rules:['Regulaminy','Tu zostaną udostępnione zatwierdzone regulaminy i zasady korzystania z portalu.'],stories:['Opowieści','Tu znajdą się opowieści i historie przedstawione przez uczestników portalu.'],contact:['Kontakt','Miejsce na zatwierdzone dane kontaktowe i formularz kontaktu z AsterA.'],documents:['Dokumenty','Tu będzie można otworzyć dokumenty i materiały źródłowe powiązane ze sprawą.'],positions:['Stanowiska stron','W tym miejscu każda strona będzie mogła przedstawić swoje stanowisko i odnieść się do materiałów.'],verify:['Weryfikacja','Tu znajdą się informacje o źródłach, sprawdzonych materiałach i statusie ich weryfikacji.']};
function showPanel(id,index){
 let title,html;
 if(id==='opinions'){
 title='Opinie';const list=index===undefined?opinions:[opinions[index]];
 html='<p class="panel-note">Przykłady fikcyjne — teksty z zaakceptowanych wizualizacji. Nie opisują prawdziwych klientów ani ocen.</p>'+list.map(r=>`<article class="panel-opinion"><strong>${r.source} · ${r.name} · ${r.rating}</strong><p>„${r.text}”</p></article>`).join('');
 }else{[title,html]=copy[id];html=`<p>${html}</p>`+(id==='faq'?'':'<p class="panel-note">Podgląd układu. Treść tej sekcji jest jeszcze do uzupełnienia.</p>');}
 document.querySelector('#panel-title').textContent=title;document.querySelector('#panel-content').innerHTML=html;panel.showModal();environment.sync();
}
document.querySelector('#cards').addEventListener('click',e=>{const card=e.target.closest('[data-card]');if(!card)return;const id=card.dataset.card;if(id==='facts'){const hidden=document.querySelector('.stage').classList.toggle('branch-hidden');card.setAttribute('aria-expanded',String(!hidden));}else showPanel(id);});
document.querySelector('#reviews').addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(b)showPanel('opinions',Number(b.dataset.review));});
document.querySelector('.close-panel').addEventListener('click',()=>panel.close());panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)panel.close();}});panel.addEventListener('close',()=>environment.sync());
// The environment owns playback only. It never rebuilds cards or panels.
const environment=(()=>{
 const video=document.querySelector('#environment-video'),button=document.querySelector('#motion'),label=button.querySelector('.motion-label'),status=document.querySelector('#environment-status'),returnFrame=document.querySelector('.return-frame');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');let preference=null,blocked=false,loaded=false,request=0,returning=false;
 try{preference=localStorage.getItem('astera-motion');}catch{}
 const saveData=Boolean(navigator.connection?.saveData)||/^(slow-2g|2g)$/.test(navigator.connection?.effectiveType||'');
 const wantsMotion=()=>preference==='on'||(preference!=='off'&&!reduced.matches&&!saveData);
 function paint(){const paused=!wantsMotion()||blocked;label.textContent=paused?'Włącz ruch tła':'Zatrzymaj tło';button.setAttribute('aria-pressed',String(paused));button.querySelector('.motion-icon').textContent=paused?'▷':'Ⅱ';}
 function load(){if(loaded)return;loaded=true;video.src='assets/otoczenie.mp4';video.load();}
 async function sync(){const token=++request;paint();if(!wantsMotion()||document.hidden||panel.open||blocked){video.pause();document.querySelector('.stage').classList.remove('reviews-fading');return;}load();try{await video.play();if(token!==request){if(!wantsMotion()||document.hidden||panel.open)video.pause();return;}status.textContent='';paint();}catch(e){if(e.name==='AbortError'||token!==request)return;blocked=true;status.textContent='Tło nieruchome';paint();}}
 button.addEventListener('click',()=>{preference=(!wantsMotion()||blocked)?'on':'off';blocked=false;try{localStorage.setItem('astera-motion',preference);}catch{}status.textContent='';sync();});
 video.addEventListener('playing',()=>{video.classList.add('ready');status.textContent='';});
 video.addEventListener('error',()=>{blocked=true;video.classList.remove('ready');status.textContent='Tło nieruchome';paint();});
 video.addEventListener('timeupdate',()=>{const t=video.currentTime;const transition=[9,17.5,26.5,35.5].some(x=>Math.abs(x-t)<.65);document.querySelector('.stage').classList.toggle('reviews-fading',transition);if(video.duration&&t>video.duration-1.15&&!returning){returning=true;returnFrame.classList.add('visible');}});
 video.addEventListener('ended',()=>{video.currentTime=0;returning=false;document.querySelector('.stage').classList.remove('reviews-fading');sync();setTimeout(()=>returnFrame.classList.remove('visible'),180);});
 document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);paint();
 requestAnimationFrame(()=>requestAnimationFrame(()=>{if('requestIdleCallback'in window)requestIdleCallback(sync,{timeout:1500});else setTimeout(sync,300);}));
 return {sync};
})();
