'use strict';
const app=document.querySelector('#app'),view=new URLSearchParams(location.search).get('view')||'reservation';
const state={stage:'start',kind:'osoba',salon:validSalon(new URLSearchParams(location.search).get('salon')),selected:null,detail:null,date:null,time:null,staff:null,clientPhone:null};let catalogue=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds={osoba:['Dla jednej osoby','Chwila tylko dla Ciebie.',0],pary:['Dla par','Wspólny relaks w jednym gabinecie.',7],rytualy:['Rytuały','Poznaj przebieg każdej ceremonii.',5]};
if(['reservation','voucher','about','contact'].includes(view))document.querySelector('body').classList.add('reservation-flow');
if(view==='about')document.querySelector('body').classList.add('about-page');
if(view==='contact')document.querySelector('body').classList.add('contact-page');
const notice='<div class="notice">Podgląd testowy — nie tworzy wizyt, zamówień ani płatności. Ceny są kopią tabel dotychczasowych stron, nie potwierdzeniem dostępności. Przed wdrożeniem sprawdzimy je z systemem.</div>';
document.querySelector('#salon-context').addEventListener('change',e=>{state.salon=validSalon(e.target.value);state.detail=null;state.selected=null;state.date=null;state.time=null;state.staff=null;if(['detail','calendar','data','done','voucher-review'].includes(state.stage))state.stage='services';render();});
document.querySelector(`[data-view="${view}"]`)?.classList.add('active');document.querySelector('#menu').onclick=()=>{const b=document.querySelector('#menu'),n=document.querySelector('#site-menu');n.hidden=!n.hidden;b.setAttribute('aria-expanded',String(!n.hidden));};
const back=(stage,text)=>stage==='categories'&&returnsToFilmMenu()?`<a class="back" href="${previewLink('menu-filmowe-salony.html',state.salon)}">← Wróć do menu</a>`:`<button class="back" data-stage="${stage}">← ${text}</button>`;
function title(t){
 if(view==='reservation'||view==='voucher')return `<div class="booking-salons" aria-label="Wybierz salon">${['ZW','SZ'].map(s=>`<button data-salon="${s}" aria-pressed="${s===state.salon}" class="${s===state.salon?'selected':''}"><img class="salon-logo" src="www-assets/thai-maliwan-mark.png" alt=""><b>${s==='ZW'?'Zwierzyniecka':'Szewska'}</b></button>`).join('')}</div><h1 class="${state.stage==='categories'?'category-heading':''}">${t}</h1>${new URLSearchParams(location.search).get('test')==='1'?notice:''}`;
 return `<p class="muted"><a href="www-komputer-luxury.html">Strona główna</a> / ${view==='voucher'?'Kup voucher':'Rezerwacja'}</p><h1>${t}</h1>${notice}`;
}
function render(){
 renderPage();syncSalonLinks(state.salon);
 if(typeof history!=='undefined'&&history.replaceState)history.replaceState(null,'',previewLink((location.search||'?view='+view)+(location.hash||''),state.salon));
}
function renderPage(){
 if(view==='plan'){app.innerHTML=title('Plan połączenia stron')+'<div class="panel"><h2>Małe, odwracalne etapy</h2><ol><li>Menu, cztery przyciski i społeczności — działający podgląd.</li><li>Rezerwacja i voucher — testowe przejścia, bez zapisu.</li><li>Pełne treści i zdjęcia podstron O nas i Kontakt — do dopasowania; istniejące adresy pozostają.</li><li>Warianty cenowe ze starych stron — w podglądzie; produkty i dostępność systemu — jeszcze niepodłączone.</li><li>Desktop, iPad, telefon, linki i błędy.</li><li>Wdrożenie produkcyjne osobnymi małymi partiami z kopią i kontrolą SEO.</li></ol><p>Makiety GitHub mają noindex,nofollow. Nie zmieniono domen, produkcyjnych URL, title, canonical, treści ani płatności.</p><p>Przegląd wszystkich dotychczasowych wizualizacji: <a href="wizualizacje.html">otwórz galerię makiet</a>.</p></div>';return;}
 if(view==='about'){app.innerHTML=renderAbout();return;}
 if(view==='contact'){app.innerHTML=renderContact();return;}
 if(state.stage==='start'&&view==='reservation'){app.innerHTML=title('Jak chcesz zarezerwować?')+'<div class="choices"><button data-stage="categories">Rezerwuję wizytę</button><button data-stage="bon">Mam bon — chcę go wykorzystać</button></div><p class="booking-preview-note">Podgląd — rezerwacje nie są jeszcze wysyłane.</p>';return;}
 if(state.stage==='bon'){app.innerHTML=title('Zarezerwuj wizytę z bonem')+back('start','Wróć')+'<section class="panel"><h2>Wpisz numer bonu</h2><p>Znajdziesz go na bonie papierowym lub elektronicznym.</p><form id="bon-form" class="fields"><label>Numer bonu<input name="bon" required autocomplete="off"></label><button class="primary">Sprawdź bon</button></form><p id="bon-result" role="status"></p></section>';return;}
 if(state.stage==='start')state.stage='categories';
 if(state.stage==='categories'&&view==='voucher'){app.innerHTML=title('Podaruj chwilę relaksu')+'<div class="categories voucher-categories">'+Object.entries(kinds).map(([k])=>`<button type="button" class="category voucher-category" data-kind="${k}"><div class="voucher-face"><span class="voucher-topline"><span class="voucher-title">Bon podarunkowy</span><span class="voucher-logo"><img src="www-assets/thai-maliwan-mark.png" alt=""><span>Maliwan<small>SPA THAI</small></span></span></span><span class="voucher-ornament" aria-hidden="true"></span><span class="voucher-ribbon" aria-hidden="true"><svg viewBox="0 0 48 94" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21 0h6v94h-6z" fill="#c6a15b"/><path d="M23 0h2v94h-2z" fill="#ebd197"/><path d="M24 29C12 12 3 18 6 27c2 7 12 5 18 2Zm0 0c12-17 21-11 18-2-2 7-12 5-18 2Z" fill="#d7b677" stroke="#98723b" stroke-width="1"/><path d="m21 32-9 19 7-2 3 5 4-22m1 0 9 19-7-2-3 5-4-22" fill="#d7b677" stroke="#98723b" stroke-width=".8"/><path d="M20 26h8v7h-8z" fill="#b68e49"/><path d="M22 27h4v5h-4z" fill="#efd59b"/></svg></span><div class="voucher-category-frame"><h2>${k==='osoba'?'Dla jednej osoby':k==='pary'?'Dla pary':'Rytuały'}</h2></div><span class="voucher-action">Wybierz bon →</span></div></button>`).join('')+'</div><p class="booking-preview-note">Podgląd — zakup i płatności nie są jeszcze podłączone.</p>';return;}
 if(state.stage==='categories'){app.innerHTML=title(view==='voucher'?'Podaruj chwilę relaksu':'Wybierz masaż')+'<div class="categories">'+Object.entries(kinds).map(([k,[t,d,img]])=>`<button class="category" data-kind="${k}"><img src="${(document.body.matches('.desktop-booking, .booking-photo-standard')?'www-assets/rezerwacje-wybrane/'+({osoba:'kategoria-osoba-klisza.png',pary:'kategoria-pary.jpg',rytualy:'kategoria-rytualy-klisza.png'}[k]):({osoba:'www-assets/kadr-1-maliwan.png',pary:'www-assets/kategoria-pary-spokojne-tlo.png',rytualy:'www-assets/kadr-5-maliwan.png'}[k]))}" alt=""><div><h2>${t}</h2><p>${d}</p><span>${view==='voucher'?'Wybierz bon':'Zobacz ofertę'} →</span></div></button>`).join('')+'</div>'+(view==='voucher'?'<p class="booking-preview-note">Podgląd — zakup i płatności nie są jeszcze podłączone.</p>':'');return;}
 if(state.stage==='services'&&view==='voucher'){app.innerHTML=voucherServices();return;}
 if(state.stage==='services'&&view==='reservation'){app.innerHTML=compactServices();return;}
 if(state.stage==='services'){const list=catalogue.filter(x=>x.salon===state.salon&&x.kind===state.kind);app.innerHTML=title(view==='voucher'?'Wybierz zabieg na voucher':'Wybierz zabieg i czas')+back('categories','Wróć do kategorii')+'<div class="choices service-salons" aria-label="Wybierz salon">'+['ZW','SZ'].map(s=>`<button data-salon="${s}" class="${s===state.salon?'selected':''}">${s==='ZW'?'Zwierzyniecka':'Szewska'}</button>`).join('')+'</div><div class="columns"><section>'+ (list.length?list.map(x=>{const idx=catalogue.indexOf(x);return `<article class="service"><img src="www-assets/scena-${kinds[state.kind][2]}.jpg" alt="Zdjęcie poglądowe kategorii"><div class="body"><h2>${esc(x.name)}</h2><p>${esc(x.text)}</p><div class="variants">${x.prices.map(p=>`<button class="variant ${state.selected?.url===x.url&&state.selected.minutes===p.minutes?'selected':''}" data-item="${idx}" data-minutes="${p.minutes}">${p.minutes} min · ${p.price} zł</button>`).join('')}</div>${x.prices.length?'':'<p>Czas i cena do pobrania z aktualnej oferty. Nie są jeszcze podłączone.</p>'}<button class="service-open" data-detail="${idx}">Pełny opis i wybór czasu →</button></div></article>`;}).join(''):'<div class="panel">Katalog tej kategorii wymaga uzupełnienia. <a href="'+(state.salon==='ZW'?'https://thaimaliwan.pl/oferta/':'https://thaimaliwanspa.pl/')+'">Otwórz aktualną ofertę →</a></div>')+'</section>'+summary()+'</div>';return;}
 if(state.stage==='detail'){const x=catalogue[state.detail],idx=state.detail;app.innerHTML=title(esc(x.name))+back('services','Wróć do oferty')+'<div class="columns"><article class="panel detail-panel"><img class="detail-image" src="www-assets/scena-'+kinds[state.kind][2]+'.jpg" alt="Zdjęcie poglądowe kategorii"><p class="detail-label">'+(state.salon==='ZW'?'Zwierzyniecka':'Szewska')+' · '+kinds[state.kind][0]+'</p><h2>Twój moment spokoju</h2><p>'+esc(x.text)+'</p><h3>Wybierz czas</h3><div class="variants">'+x.prices.map(p=>`<button class="variant ${state.selected?.url===x.url&&state.selected.minutes===p.minutes?'selected':''}" data-item="${idx}" data-minutes="${p.minutes}">${p.minutes} min · ${p.price} zł</button>`).join('')+'</div>'+(x.prices.length?'':'<p>Warianty tej usługi wymagają jeszcze potwierdzenia. Nie wybieramy ceny za Ciebie.</p>')+'<details class="source-link"><summary>Dotychczasowa strona — źródło oferty</summary><a href="'+esc(x.url)+'" target="_blank" rel="noopener">Porównaj opis i warianty ↗</a></details></article>'+summary()+'</div>';return;}
 if(state.stage==='voucher-review'){const x=state.selected;app.innerHTML=title('Twój voucher — podsumowanie')+back('services','Zmień wariant')+'<section class="panel"><p class="detail-label">'+(state.salon==='ZW'?'Zwierzyniecka':'Szewska')+'</p><h2>'+esc(x.name)+'</h2><p>'+x.minutes+' minut · '+x.price+' zł</p><p>Wybrany wariant jest gotowy do przyszłego połączenia ze sklepem. Nie utworzono zamówienia ani płatności.</p><p>Ekran płatności pozostaje bez zmian. W tej makiecie kończymy przed jego uruchomieniem.</p><details class="source-link"><summary>Dotychczasowy sklep</summary><a href="'+esc(x.buyUrl)+'" target="_blank" rel="noopener">Otwórz istniejący zakup bonu ↗</a><p>To osobna strona sklepu, poza testem makiety.</p></details></section>';return;}
 if(state.stage==='calendar'){app.innerHTML=title('Wybierz dzień i godzinę')+back(view==='reservation'||state.detail===null?'services':'detail','Zmień zabieg')+'<p class="steps">✓ Zabieg · <strong>2 Termin</strong> · 3 Dane</p><div class="columns"><section class="panel"><h2>Październik 2026</h2><div class="calendar">'+['Pn','Wt','Śr','Cz','Pt','So','Nd'].map(d=>`<span class="day-name">${d}</span>`).join('')+'<span></span><span></span><span></span>'+Array.from({length:31},(_,i)=>`<button data-date="${i+1}" class="${state.date===i+1?'selected':''}" ${i<2?'disabled':''}>${i+1}</button>`).join('')+'</div><h3>Godziny przykładowe</h3><div class="times">'+['12:00','13:30','15:00','17:30'].map(t=>`<button class="time ${state.time===t?'selected':''}" data-time="${t}">${t}</button>`).join('')+'</div><p>To przykłady, nie dostępność salonu.</p>'+staffPicker()+'</section>'+summary()+'</div>';return;}
 if(state.stage==='data'){app.innerHTML=title('Twoje dane')+back('calendar','Zmień termin')+'<p class="steps">✓ Zabieg · ✓ Termin · <strong>3 Dane</strong></p><div class="columns"><section class="panel client-panel">'+clientForm()+ '</section>'+summary()+'</div>';return;}
 if(state.stage==='done'){app.innerHTML=title('Test przejścia zakończony')+'<div class="panel"><h2>Nie utworzono rezerwacji</h2><p>Przetestowano wybór salonu, usługi, wariantu i przykładowego terminu. Dane formularza nie zostały wysłane.</p><a href="?view=reservation">Zacznij ponownie →</a></div>';}
}
function offerPhoto(x,index){
 if(document.body.matches('.desktop-booking, .booking-photo-standard')&&x.kind==='pary'){
  const selected=['tajski-wzorzec.png','olejki.jpg','kamienie-zabieg.png','swiece-wzorzec.png','stemple-wzorzec.png','romantyczny-wzorzec.png'][index];
  if(selected)return 'www-assets/rezerwacje-pary/'+selected;
 }

 if(document.body.matches('.desktop-booking, .booking-photo-standard')){
  const images={
   osoba:['rezerwacje-wybrane/tajski-klisza.png','rezerwacje-wybrane/olejki-rolka.png','rezerwacje-wybrane/kamienie-klisza.png','rezerwacje-wybrane/swieca-klisza.png','oferta-spojna/sportowy-klisza.png','rezerwacje-wybrane/lomi.jpg','rezerwacje-pary/stemple-wzorzec.png','oferta-spojna/seniorGen.png','oferta-spojna/mlodziez.png','oferta-spojna/cztery-rece.png','oferta-spojna/prenatal.png','oferta-spojna/lifting.png','oferta-spojna/pielegnacja.png','oferta-spojna/plecy.png','oferta-spojna/refleks-glowy.png','oferta-spojna/stopy.png','oferta-spojna/modelujacy.png'],
   rytualy:['rezerwacje-pary/stemple-wzorzec.png','oferta-spojna/kamienie-ziola.png','oferta-spojna/detoks-odnowa.png','oferta-spojna/kwiat-duszy.png','oferta-spojna/refleks-glowy.png','rezerwacje-wybrane/tajski-klisza.png','rezerwacje-wybrane/olejki-rolka.png','rezerwacje-pary/romantyczny-wzorzec.png']
  };
  const selected=images[x.kind]?.[index];
  if(selected)return 'www-assets/'+selected;
 }
 const dir='www-assets/oferta-zdjecia/';
 const single=['www-assets/kadr-3-szkola-maliwan.webp',dir+'olejki-szewska.jpg',dir+'kamienie-szewska.jpg',dir+'r7-oil-aroma.jpg',dir+'sportowy-cieply.png',dir+'k2-olejki.jpg','www-assets/kadr-5-maliwan.png',dir+'senior-cieply.png',dir+'mlodziez-cieply.png',dir+'cztery-rece.png',dir+'prenatal.jpg','www-assets/kadr-6-maliwan.png',dir+'r3-detoks.jpg','www-assets/kadr-2-maliwan.png',dir+'refleks-glowy.png',dir+'c7-stopy.jpg',dir+'szkola-praca-manualna.webp'];
 const pair=['www-assets/kategoria-pary-spokojne-tlo.png',dir+'p1-klasyczny.jpg','www-assets/kadr-4-maliwan.png',dir+'k4-swiece.jpg','www-assets/kadr-5-maliwan.png',dir+'p6-romantyczny.jpg'];
 const rituals=['www-assets/kadr-5-maliwan.png','www-assets/kadr-4-maliwan.png',dir+'r3-detoks.jpg',dir+'r4-kwiat-duszy.jpg','www-assets/kadr-0-maliwan.png','www-assets/kadr-3-szkola-maliwan.webp',dir+'r7-oil-aroma.jpg',dir+'r1-krolewski.jpg'];
 return (x.kind==='osoba'?single:x.kind==='pary'?pair:rituals)[index]||dir+'k1-tradycyjny.jpg';
}
function voucherServices(){
 const list=catalogue.filter(x=>x.salon===state.salon&&x.kind===state.kind);
 const cards=list.map((x,index)=>{
  const idx=catalogue.indexOf(x),selected=state.selected?.url===x.url;
  return `<article class="offer-tile voucher-product"><img class="voucher-treatment-strip" src="${offerPhoto(x,index)}" alt="Zdjęcie poglądowe zabiegu" loading="lazy"><div class="gift-print"><span class="gift-brand"><img src="www-assets/thai-maliwan-mark.png" alt="">Maliwan</span><span class="gift-heading">Bon podarunkowy</span><span class="voucher-ornament" aria-hidden="true"></span><span class="voucher-ribbon" aria-hidden="true"><svg viewBox="0 0 48 94" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21 0h6v94h-6z" fill="#c6a15b"/><path d="M23 0h2v94h-2z" fill="#ebd197"/><path d="M24 29C12 12 3 18 6 27c2 7 12 5 18 2Zm0 0c12-17 21-11 18-2-2 7-12 5-18 2Z" fill="#d7b677" stroke="#98723b" stroke-width="1"/><path d="m21 32-9 19 7-2 3 5 4-22m1 0 9 19-7-2-3 5-4-22" fill="#d7b677" stroke="#98723b" stroke-width=".8"/><path d="M20 26h8v7h-8z" fill="#b68e49"/><path d="M22 27h4v5h-4z" fill="#efd59b"/></svg></span><h2>${esc(x.name)}</h2><span class="gift-recipient">${state.kind==='osoba'?'Dla jednej osoby':state.kind==='pary'?'Dla pary':'Rytuał Thai Maliwan'}</span></div><div class="variants" role="group" aria-label="${esc(x.name)} — czas i cena">${x.prices.map(p=>`<button type="button" aria-pressed="${selected&&state.selected.minutes===p.minutes}" class="variant ${selected&&state.selected.minutes===p.minutes?'selected':''}" data-item="${idx}" data-minutes="${p.minutes}"><span>${p.minutes} min</span><b>${p.price} zł</b></button>`).join('')}</div>${x.prices.length?'':'<p class="offer-intro">Warianty wymagają jeszcze potwierdzenia.</p>'}${selected?'<button type="button" class="primary offer-next" data-stage="voucher-review">Wybierz ten bon →</button>':''}<details class="offer-description"><summary>O masażu — pełny opis</summary><p>${esc(x.text)}</p></details></article>`;
 }).join('');
 return title('Wybierz zabieg na voucher')+back('categories','Wróć do kategorii')+`<section class="offer-grid voucher-products" aria-label="${kinds[state.kind][0]}">${cards||'<p>Oferta tej kategorii wymaga uzupełnienia.</p>'}</section><p class="offer-help">Wybierz czas i cenę na bonie. Podgląd nie uruchamia zakupu ani płatności.</p>`;
}
function compactServices(){
 const list=catalogue.filter(x=>x.salon===state.salon&&x.kind===state.kind);
 const hints=[[/sport/i,'Intensywna praca z mięśniami.'],[/senior/i,'Spokojny masaż dopasowany do seniorów.'],[/prenatal/i,'Delikatna chwila relaksu w ciąży.'],[/dzieci|młodzież/i,'Łagodny relaks dla młodszych gości.'],[/cztery ręce/i,'Dwie masażystki, jeden rytm.'],[/kamieni/i,'Ciepło kamieni i spokojny relaks.'],[/świec/i,'Ciepły olejek i aromat świecy.'],[/stempl/i,'Ciepłe zioła i rytmiczne dociski.'],[/Lomi/i,'Płynne ruchy w tajskiej wersji.'],[/olejk|Oil Aroma/i,'Aromatyczny olejek i odprężenie.'],[/lifting/i,'Delikatna praca z twarzą i głową.'],[/Kobido/i,'Precyzyjna praca z twarzą i głową.'],[/pielęgn/i,'Chwila pielęgnacji dla twarzy.'],[/refleksoterapii stóp/i,'Uważna praca ze stopami.'],[/refleksoterapii głowy/i,'Spokojna praca z głową.'],[/modeluj/i,'Ukierunkowana praca z ciałem.'],[/głowy, pleców/i,'Relaks głowy, pleców i ramion.'],[/Tradycyjny/i,'Ucisk, rozciąganie i praca z ciałem.']];
 const cards=list.map(x=>{
  const idx=catalogue.indexOf(x),hint=hints.find(([re])=>re.test(x.name));
  const photo=offerPhoto(x,list.indexOf(x));
  return `<article class="offer-tile"><img class="offer-photo" src="${photo}" alt="Zdjęcie poglądowe zabiegu" loading="lazy"><h2>${esc(x.name)}</h2><p class="offer-intro">${hint?hint[1]:'Spokojna ceremonia pełna relaksu.'}</p><div class="variants">${x.prices.map(p=>`<button aria-pressed="${state.selected?.url===x.url&&state.selected.minutes===p.minutes}" class="variant ${state.selected?.url===x.url&&state.selected.minutes===p.minutes?'selected':''}" data-item="${idx}" data-minutes="${p.minutes}"><span>${p.minutes} min</span><b>${p.price} zł</b></button>`).join('')}</div>${state.selected?.url===x.url?'<button type="button" class="primary offer-next" data-stage="calendar">Wybierz dzień i godzinę →</button>':''}<details class="offer-description"><summary>Pełny opis</summary><p>${esc(x.text)}</p></details></article>`;
 }).join('');
 return title('Wybierz zabieg i czas')+back('categories','Wróć do kategorii')+`<section class="offer-grid" aria-label="${kinds[state.kind][0]}">${cards||'<p>Oferta tej kategorii wymaga uzupełnienia.</p>'}</section>`+(state.selected?`<div class="offer-selection"><p><b>${esc(state.selected.name)}</b><span>${state.selected.minutes} min · ${state.selected.price} zł</span></p><button class="primary" data-stage="calendar">Wybierz termin →</button></div>`:'<p class="offer-help">Wybierz czas i cenę przy wybranej usłudze.</p>');
}
function normalizeClientPhone(value){
 let digits=String(value).replace(/[^0-9]/g,'');
 if(String(value).trim().startsWith('00')&&digits.length>9)digits=digits.slice(2);
 if(digits.length===9)digits='48'+digits;
 return digits.length>=8&&digits.length<=15?'+'+digits:null;
}
function clientForm(){
 const note='<p class="client-test-note">Użyj fikcyjnych danych testowych. Wyszukiwanie klienta i wysyłanie rezerwacji nie są jeszcze podłączone.</p>';
 if(!state.clientPhone)return '<h2>Zacznij od telefonu</h2><p class="client-intro">Podaj numer, którego używasz przy rezerwacjach.</p><form id="client-phone-form" class="fields"><label>Numer telefonu<input name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="24" placeholder="np. +48 000 000 000" required aria-describedby="client-phone-help client-phone-error"></label><p id="client-phone-help" class="client-help">Po podłączeniu systemu ten numer pomoże odnaleźć Twoje wcześniejsze dane.</p><p id="client-phone-error" class="client-error" role="alert"></p><button class="primary" type="submit">Dalej →</button></form>'+note;
 return '<h2>Uzupełnij dane</h2><div class="client-phone-line"><span>Telefon: <b>'+esc(state.clientPhone)+'</b></span><button type="button" class="back" data-edit-phone="1">Zmień numer</button></div><p class="client-help">W podglądzie uzupełnij dane ręcznie. Jeśli rezerwujesz pierwszy raz, wystarczy imię i e-mail.</p><form id="demo-form" class="fields"><label>Imię<input name="firstName" autocomplete="given-name" maxlength="60" required></label><label>Adres e-mail<input name="email" type="email" inputmode="email" autocomplete="email" maxlength="254" required></label><p class="client-help">E-mail będzie służył do potwierdzenia rezerwacji.</p><button class="primary" type="submit">Sprawdź podsumowanie testu →</button></form>'+note;
}
function bookingStaff(){return maliwanInfo.salons.find(s=>s.id===state.salon)?.staff||[];}
function staffPicker(){
 const options=[{id:'any',label:'Dowolna dostępna'},...bookingStaff().map(name=>({id:name,label:name}))];
 return `<section class="booking-staff" aria-labelledby="booking-staff-title"><h3 id="booking-staff-title">Wybierz masażystkę</h3><p class="staff-help">Opcjonalnie — możesz zostawić wybór nam.</p><div class="staff-options" role="group" aria-label="Preferowana masażystka">${options.map(o=>`<button type="button" data-staff="${esc(o.id)}" aria-pressed="${(state.staff||'any')===o.id}" class="staff-option ${(state.staff||'any')===o.id?'selected':''}"><span class="staff-initial" aria-hidden="true">${o.id==='any'?'✦':esc(o.label.slice(0,1))}</span><span>${esc(o.label)}</span></button>`).join('')}</div><p class="staff-help">Lista zespołu w podglądzie. Dostępność dla dnia, godziny i zabiegu zostanie podłączona do kalendarza.${state.kind==='pary'||/cztery ręce/i.test(state.selected?.name||'')?' Wybierasz preferowaną osobę; pozostały skład zostanie dobrany według dostępności.':''}</p></section>`;
}
function summary(){let x=state.selected;return '<aside class="summary"><h2>'+ (view==='voucher'?'Twój voucher':'Twój wybór')+'</h2><p>'+ (state.salon==='ZW'?'Zwierzyniecka':'Szewska')+'</p>'+ (x?`<p>${esc(x.name)}</p><p>${x.minutes} minut</p>${view==='reservation'&&['calendar','data','done'].includes(state.stage)?`<p class="staff-summary">Masażystka: <b>${esc(state.staff||'Dowolna dostępna')}</b></p>`:''}${state.date?`<p>${state.date} października 2026${state.time?' · '+state.time:''}</p>`:''}<strong>${x.price} zł</strong>`:'<p>Wybierz dostępny wariant.</p>')+(view==='voucher'?'<button class="primary" id="buy-demo" '+(!x?'disabled':'')+'>Kup voucher →</button><p>Podgląd nie uruchamia płatności.</p>':(state.stage==='services'||state.stage==='detail')?'<button class="primary" data-stage="calendar" '+(!x?'disabled':'')+'>Wybierz termin →</button>':state.stage==='calendar'?'<button class="primary" data-stage="data" '+(!state.date||!state.time?'disabled':'')+'>Dalej — Twoje dane →</button>':'')+'</aside>';}
app.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.stage){state.stage=el.dataset.stage;render();if(state.stage==='calendar'&&typeof window!=='undefined'){window.scrollTo({top:0,behavior:'instant'});}}if(el.dataset.kind){state.kind=el.dataset.kind;state.stage='services';state.selected=null;state.detail=null;state.date=null;state.time=null;state.staff=null;render();}if(el.dataset.detail!==undefined){state.detail=Number(el.dataset.detail);const x=catalogue[state.detail];if(state.selected?.url!==x.url)state.selected=null;state.stage='detail';render();}if(el.dataset.salon){state.salon=el.dataset.salon;state.detail=null;state.selected=null;state.date=null;state.time=null;state.staff=null;render();}if(el.dataset.item){const x=catalogue[Number(el.dataset.item)],p=x.prices.find(p=>p.minutes===Number(el.dataset.minutes));state.detail=Number(el.dataset.item);state.selected={...x,...p};state.date=null;state.time=null;state.staff=null;render();}if(el.dataset.date){state.date=Number(el.dataset.date);state.time=null;render();}if(el.dataset.time){state.time=el.dataset.time;render();}if(el.dataset.staff!==undefined&&state.stage==='calendar'){const name=el.dataset.staff;if(name==='any'||bookingStaff().includes(name)){state.staff=name==='any'?null:name;render();const focusButton=Array.from(document.querySelectorAll('[data-staff]')).find(b=>b.dataset.staff===name);focusButton?.focus();}}if(el.dataset.editPhone&&state.stage==='data'){state.clientPhone=null;render();}if(el.id==='buy-demo'&&state.selected){state.stage='voucher-review';render();}});
app.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='contact-demo-form'){document.querySelector('#contact-demo-result').textContent='Formularz testowy sprawdzony. Wiadomość nie została wysłana ani zapisana.';}if(e.target.id==='bon-form')document.querySelector('#bon-result').textContent='Sprawdzanie bonów nie jest jeszcze podłączone. Nie uznajemy tego bonu za ważny ani opłacony.';if(e.target.id==='client-phone-form'){
 const value=e.target.elements.phone.value.trim();
 const normalized=/^\+?[0-9 ()-]+$/.test(value)?normalizeClientPhone(value):null;
 if(!normalized){document.querySelector('#client-phone-error').textContent='Podaj poprawny numer telefonu, z numerem kierunkowym dla numerów zagranicznych.';return;}
 state.clientPhone=normalized;render();
 }if(e.target.id==='demo-form'){
 if(!state.clientPhone||!e.target.elements?.firstName?.value.trim()||!e.target.elements?.email?.value.trim())return;
 if(e.target.checkValidity&&!e.target.checkValidity()){e.target.reportValidity();return;}
 state.stage='done';state.clientPhone=null;render();
 }});
fetch('www-assets/oferta.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('catalogue');return r.json();}).then(data=>{catalogue=data;const query=new URLSearchParams(location.search),kind=query.get('kind'),salon=query.get('salon');if(['ZW','SZ'].includes(salon))state.salon=salon;if(Object.prototype.hasOwnProperty.call(kinds,kind)){state.kind=kind;state.stage='services';}render();}).catch(()=>{app.innerHTML='<h1>Nie udało się wczytać podglądu</h1><p>Odśwież stronę albo wróć do makiety głównej.</p><a href="www-komputer-luxury.html">Wróć →</a>';});
