'use strict';
const app=document.querySelector('#app'),view=new URLSearchParams(location.search).get('view')||'reservation';
const state={stage:'start',kind:'osoba',salon:'ZW',selected:null,detail:null,date:null,time:null};let catalogue=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds={osoba:['Dla jednej osoby','Chwila tylko dla Ciebie.',0],pary:['Dla par','Wspólny relaks w jednym gabinecie.',7],rytualy:['Rytuały','Poznaj przebieg każdej ceremonii.',5]};
const notice='<div class="notice">Podgląd testowy — nie tworzy wizyt, zamówień ani płatności. Ceny są kopią tabel dotychczasowych stron, nie potwierdzeniem dostępności. Przed wdrożeniem sprawdzimy je z systemem.</div>';
document.querySelector(`[data-view="${view}"]`)?.classList.add('active');document.querySelector('#menu').onclick=()=>{const b=document.querySelector('#menu'),n=document.querySelector('#site-menu');n.hidden=!n.hidden;b.setAttribute('aria-expanded',String(!n.hidden));};
const back=(stage,text)=>`<button class="back" data-stage="${stage}">← ${text}</button>`;
function title(t){return `<p class="muted"><a href="mobilna-v14.html">Strona główna</a> / ${view==='voucher'?'Kup voucher':'Rezerwacja'}</p><h1>${t}</h1>${notice}`;}
function render(){
 if(view==='plan'){app.innerHTML=title('Plan połączenia stron')+'<div class="panel"><h2>Małe, odwracalne etapy</h2><ol><li>Menu, cztery przyciski i społeczności — działający podgląd.</li><li>Rezerwacja i voucher — testowe przejścia, bez zapisu.</li><li>Pełne treści i zdjęcia podstron O nas i Kontakt — do dopasowania; istniejące adresy pozostają.</li><li>Warianty cenowe ze starych stron — w podglądzie; produkty i dostępność systemu — jeszcze niepodłączone.</li><li>Desktop, iPad, telefon, linki i błędy.</li><li>Wdrożenie produkcyjne osobnymi małymi partiami z kopią i kontrolą SEO.</li></ol><p>Makiety GitHub mają noindex,nofollow. Nie zmieniono domen, produkcyjnych URL, title, canonical, treści ani płatności.</p><p>Przegląd wszystkich dotychczasowych wizualizacji: <a href="wizualizacje.html">otwórz galerię makiet</a>.</p></div>';return;}
 if(view==='about'){app.innerHTML=renderAbout();return;}
 if(view==='contact'){app.innerHTML=renderContact();return;}
 if(state.stage==='start'&&view==='reservation'){app.innerHTML=title('Jak chcesz zarezerwować?')+'<div class="choices"><button data-stage="categories">Bez bonu — rezerwuję wizytę</button><button data-stage="bon">Mam bon — chcę go wykorzystać</button></div>';return;}
 if(state.stage==='bon'){app.innerHTML=title('Zarezerwuj wizytę z bonem')+back('start','Wróć')+'<section class="panel"><h2>Wpisz numer bonu</h2><p>Znajdziesz go na bonie papierowym lub elektronicznym.</p><form id="bon-form" class="fields"><label>Numer bonu<input name="bon" required autocomplete="off"></label><button class="primary">Sprawdź bon</button></form><p id="bon-result" role="status"></p></section>';return;}
 if(state.stage==='start')state.stage='categories';
 if(state.stage==='categories'){app.innerHTML=title(view==='voucher'?'Podaruj chwilę relaksu':'Dla kogo rezerwujesz?')+(view==='reservation'?back('start','Wybór rezerwacji'):'')+'<div class="categories">'+Object.entries(kinds).map(([k,[t,d,img]])=>`<button class="category" data-kind="${k}"><img src="www-assets/scena-${img}.jpg" alt=""><div><h2>${t}</h2><p>${d}</p><span>${view==='voucher'?'Wybierz bon':'Zobacz ofertę'} →</span></div></button>`).join('')+'</div>';return;}
 if(state.stage==='services'){const list=catalogue.filter(x=>x.salon===state.salon&&x.kind===state.kind);app.innerHTML=title(view==='voucher'?'Wybierz zabieg na voucher':'Wybierz zabieg i czas')+back('categories','Wróć do kategorii')+'<div class="choices" aria-label="Wybierz salon">'+['ZW','SZ'].map(s=>`<button data-salon="${s}" class="${s===state.salon?'selected':''}">${s==='ZW'?'Zwierzyniecka':'Szewska'}</button>`).join('')+'</div><div class="columns"><section>'+ (list.length?list.map(x=>{const idx=catalogue.indexOf(x);return `<article class="service"><img src="www-assets/scena-${kinds[state.kind][2]}.jpg" alt="Zdjęcie poglądowe kategorii"><div class="body"><h2>${esc(x.name)}</h2><p>${esc(x.text)}</p><div class="variants">${x.prices.map(p=>`<button class="variant ${state.selected?.url===x.url&&state.selected.minutes===p.minutes?'selected':''}" data-item="${idx}" data-minutes="${p.minutes}">${p.minutes} min · ${p.price} zł</button>`).join('')}</div>${x.prices.length?'':'<p>Czas i cena do pobrania z aktualnej oferty. Nie są jeszcze podłączone.</p>'}<button class="service-open" data-detail="${idx}">Pełny opis i wybór czasu →</button></div></article>`;}).join(''):'<div class="panel">Katalog tej kategorii wymaga uzupełnienia. <a href="'+(state.salon==='ZW'?'https://thaimaliwan.pl/oferta/':'https://thaimaliwanspa.pl/')+'">Otwórz aktualną ofertę →</a></div>')+'</section>'+summary()+'</div>';return;}
 if(state.stage==='detail'){const x=catalogue[state.detail],idx=state.detail;app.innerHTML=title(esc(x.name))+back('services','Wróć do oferty')+'<div class="columns"><article class="panel detail-panel"><img class="detail-image" src="www-assets/scena-'+kinds[state.kind][2]+'.jpg" alt="Zdjęcie poglądowe kategorii"><p class="detail-label">'+(state.salon==='ZW'?'Zwierzyniecka':'Szewska')+' · '+kinds[state.kind][0]+'</p><h2>Twój moment spokoju</h2><p>'+esc(x.text)+'</p><h3>Wybierz czas</h3><div class="variants">'+x.prices.map(p=>`<button class="variant ${state.selected?.url===x.url&&state.selected.minutes===p.minutes?'selected':''}" data-item="${idx}" data-minutes="${p.minutes}">${p.minutes} min · ${p.price} zł</button>`).join('')+'</div>'+(x.prices.length?'':'<p>Warianty tej usługi wymagają jeszcze potwierdzenia. Nie wybieramy ceny za Ciebie.</p>')+'<details class="source-link"><summary>Dotychczasowa strona — źródło oferty</summary><a href="'+esc(x.url)+'" target="_blank" rel="noopener">Porównaj opis i warianty ↗</a></details></article>'+summary()+'</div>';return;}
 if(state.stage==='voucher-review'){const x=state.selected;app.innerHTML=title('Twój voucher — podsumowanie')+back('detail','Zmień wariant')+'<section class="panel"><p class="detail-label">'+(state.salon==='ZW'?'Zwierzyniecka':'Szewska')+'</p><h2>'+esc(x.name)+'</h2><p>'+x.minutes+' minut · '+x.price+' zł</p><p>Wybrany wariant jest gotowy do przyszłego połączenia ze sklepem. Nie utworzono zamówienia ani płatności.</p><p>Ekran płatności pozostaje bez zmian. W tej makiecie kończymy przed jego uruchomieniem.</p><details class="source-link"><summary>Dotychczasowy sklep</summary><a href="'+esc(x.buyUrl)+'" target="_blank" rel="noopener">Otwórz istniejący zakup bonu ↗</a><p>To osobna strona sklepu, poza testem makiety.</p></details></section>';return;}
 if(state.stage==='calendar'){app.innerHTML=title('Wybierz dzień i godzinę')+back(state.detail===null?'services':'detail','Zmień zabieg')+'<p class="steps">✓ Zabieg · <strong>2 Termin</strong> · 3 Dane</p><div class="columns"><section class="panel"><h2>Październik 2026</h2><div class="calendar">'+['Pn','Wt','Śr','Cz','Pt','So','Nd'].map(d=>`<span class="day-name">${d}</span>`).join('')+'<span></span><span></span><span></span>'+Array.from({length:31},(_,i)=>`<button data-date="${i+1}" class="${state.date===i+1?'selected':''}" ${i<2?'disabled':''}>${i+1}</button>`).join('')+'</div><h3>Godziny przykładowe</h3><div class="times">'+['12:00','13:30','15:00','17:30'].map(t=>`<button class="time ${state.time===t?'selected':''}" data-time="${t}">${t}</button>`).join('')+'</div><p>To przykłady, nie dostępność salonu.</p></section>'+summary()+'</div>';return;}
 if(state.stage==='data'){app.innerHTML=title('Twoje dane')+back('calendar','Zmień termin')+'<div class="columns"><section class="panel"><form id="demo-form" class="fields"><p>Użyj fikcyjnych danych testowych. Formularz niczego nie wysyła ani nie zapisuje.</p><label>Imię<input name="firstName" required autocomplete="off"></label><label>Telefon<input name="phone" type="tel" required autocomplete="off"></label><label>E-mail<input name="email" type="email" required autocomplete="off"></label><button class="primary">Sprawdź podsumowanie testu →</button></form></section>'+summary()+'</div>';return;}
 if(state.stage==='done'){app.innerHTML=title('Test przejścia zakończony')+'<div class="panel"><h2>Nie utworzono rezerwacji</h2><p>Przetestowano wybór salonu, usługi, wariantu i przykładowego terminu. Dane formularza nie zostały wysłane.</p><a href="?view=reservation">Zacznij ponownie →</a></div>';}
}
function summary(){let x=state.selected;return '<aside class="summary"><h2>'+ (view==='voucher'?'Twój voucher':'Twój wybór')+'</h2><p>'+ (state.salon==='ZW'?'Zwierzyniecka':'Szewska')+'</p>'+ (x?`<p>${esc(x.name)}</p><p>${x.minutes} minut</p>${state.date?`<p>${state.date} października 2026${state.time?' · '+state.time:''}</p>`:''}<strong>${x.price} zł</strong>`:'<p>Wybierz dostępny wariant.</p>')+(view==='voucher'?'<button class="primary" id="buy-demo" '+(!x?'disabled':'')+'>Kup voucher →</button><p>Podgląd nie uruchamia płatności.</p>':(state.stage==='services'||state.stage==='detail')?'<button class="primary" data-stage="calendar" '+(!x?'disabled':'')+'>Wybierz termin →</button>':state.stage==='calendar'?'<button class="primary" data-stage="data" '+(!state.date||!state.time?'disabled':'')+'>Dalej — Twoje dane →</button>':'')+'</aside>';}
app.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.stage){state.stage=el.dataset.stage;render();}if(el.dataset.kind){state.kind=el.dataset.kind;state.stage='services';state.selected=null;state.detail=null;state.date=null;state.time=null;render();}if(el.dataset.detail!==undefined){state.detail=Number(el.dataset.detail);const x=catalogue[state.detail];if(state.selected?.url!==x.url)state.selected=null;state.stage='detail';render();}if(el.dataset.salon){state.salon=el.dataset.salon;state.detail=null;state.selected=null;state.date=null;state.time=null;render();}if(el.dataset.item){const x=catalogue[Number(el.dataset.item)],p=x.prices.find(p=>p.minutes===Number(el.dataset.minutes));state.detail=Number(el.dataset.item);state.selected={...x,...p};state.date=null;state.time=null;render();}if(el.dataset.date){state.date=Number(el.dataset.date);state.time=null;render();}if(el.dataset.time){state.time=el.dataset.time;render();}if(el.id==='buy-demo'&&state.selected){state.stage='voucher-review';render();}});
app.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='contact-demo-form'){document.querySelector('#contact-demo-result').textContent='Formularz testowy sprawdzony. Wiadomość nie została wysłana ani zapisana.';}if(e.target.id==='bon-form')document.querySelector('#bon-result').textContent='Sprawdzanie bonów nie jest jeszcze podłączone. Nie uznajemy tego bonu za ważny ani opłacony.';if(e.target.id==='demo-form'){state.stage='done';render();}});
fetch('www-assets/oferta.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('catalogue');return r.json();}).then(data=>{catalogue=data;const query=new URLSearchParams(location.search),kind=query.get('kind'),salon=query.get('salon');if(['ZW','SZ'].includes(salon))state.salon=salon;if(Object.prototype.hasOwnProperty.call(kinds,kind)){state.kind=kind;state.stage='services';}render();}).catch(()=>{app.innerHTML='<h1>Nie udało się wczytać podglądu</h1><p>Odśwież stronę albo wróć do makiety głównej.</p><a href="mobilna-v14.html">Wróć →</a>';});
